version: '3.8'
services:
  app:
    container_name: backend
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      DATABASE_URI: mongodb://localhost:27017
    ports:
      - '4000:4000'
    depends_on:
      - database

  database:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
